### PR TITLE
Update decidim

### PR DESCRIPTION
**Pull request by mrcasals**
#### :tophat: What? Why?
Update decidim to the latest version

#### :pushpin: Related Issues
None

#### :clipboard: Subtasks
None

### CODE REVIEW

**Comment by oriolgual** [comment]
@andreslucena @arnaumonty please review de test app and approve this if you're OK.

@mrcasals anything special they should review?

**Comment by mrcasals** [comment]
The changes this updates brings are found here:

https://github.com/AjuntamentdeBarcelona/decidim/compare/c1a80c0f354da6708908ed220a72729fe70e8f40...master

There aren't many of them that would affect you directly. I'd say that the only change that affects you is that proposal answers now have a rich text editor instead of a plain one, so you can add links and so.

**Comment by andreslucena** [comment]
Ok, thanks! We'll review it and tell you guys something tomorrow with @arnaumonty

**Comment by andreslucena** [comment]
We need to fix this first before merging: https://github.com/AjuntamentdeBarcelona/decidim/issues/1166

**Comment by andreslucena** [comment]
Another fix that's needed before merging: 

https://github.com/AjuntamentdeBarcelona/decidim/issues/875

**Comment by mrcasals** [comment]
@andreslucena I'm working on fixing these issues, thanks for reporting them! Once they are merged I'll update this PR so that you can check that everything works as expected.

**Comment by mrcasals** [comment]
@andreslucena I've updated this PR so that all the issues you reported are fixed. 

You can see the diff here:

https://github.com/AjuntamentdeBarcelona/decidim/compare/c1a80c0f354da6708908ed220a72729fe70e8f40...2d86d485d6f7947ce64f5f4d605057cf70a2fc2b

There are no new changes that affect your installation, as you can see from the commit messages.

So the relevant merged PRs that this update includes are:

- https://github.com/AjuntamentdeBarcelona/decidim/pull/1119 (improved mobile styles for processes)
- https://github.com/AjuntamentdeBarcelona/decidim/pull/1156 (Increase official image sizes)
- https://github.com/AjuntamentdeBarcelona/decidim/pull/1161 + https://github.com/AjuntamentdeBarcelona/decidim/pull/1169 (rich text for proposal answers)
- https://github.com/AjuntamentdeBarcelona/decidim/pull/1171 (fix title in admin section)
- https://github.com/AjuntamentdeBarcelona/decidim/pull/1173 (fix process header layout)

Please check that again using the review app :)

**Comment by andreslucena** [comment]
@mrcasals can we also add https://github.com/AjuntamentdeBarcelona/decidim/issues/1153 ?

**Comment by mrcasals** [comment]
@andreslucena I've updated decidim to the latest version so we can include https://github.com/AjuntamentdeBarcelona/decidim/issues/1153.

Apart from those listed in the previous message, new merged PRs this update includes are:

- https://github.com/AjuntamentdeBarcelona/decidim/issues/1175 (update Ruby version)
- https://github.com/AjuntamentdeBarcelona/decidim/issues/1176 (List collaborators in admin)
- https://github.com/AjuntamentdeBarcelona/decidim/issues/1177 (add category select prompt in filters)
- https://github.com/AjuntamentdeBarcelona/decidim/issues/1001 (use Typescript in React components)
- https://github.com/AjuntamentdeBarcelona/decidim/issues/1178 (Validate avatar size and dimensions)
- https://github.com/AjuntamentdeBarcelona/decidim/issues/1189 (do not delete banner iamges when updating a process)

@andreslucena you will need to re-review this.

**Comment by andreslucena** [comment]
The only bug I've found is "Category prompt" that is missing the translation (AjuntamentdeBarcelona/decidim#1177)

**Comment by mrcasals** [comment]
@andreslucena sorry, my bad. I'm waiting for tests to pass for the translation PR, and once it's merged I'll reupdate this one.

**Comment by andreslucena** [comment]
@mrcasals ok, when that's done you can merge and deploy to prod

**Comment by oriolgual** [comment]
@andreslucena updated again! https://decidim-barcelona-pr-89.herokuapp.com

**Comment by andreslucena** [comment]
Perfect, OK for everything, let's merge and deploy :1st_place_medal:

**Pull request merged**
