### PR TITLE
Update decidim

### LINKED ISSUE #92: [New Admin] - Debates section
#### :tophat: User Story

The debates admin section needs to follow the same style and markup as the other sections.

#### :clipboard: Related documentation

None

#### :dart: Acceptance criteria

The debates admin section looks wonderful.

#### :pushpin: Related issues

- This cannot be started until https://github.com/AjuntamentdeBarcelona/decidim/pull/1101 is merged.

### PR DESCRIPTION
**Pull request by beagleknight**
#### :tophat: What? Why?

Update decidim to the latest version.

#### :pushpin: Related Issues

- Closes #92

### CODE REVIEW

**Comment by beagleknight** [comment]
Hey @andreslucena ! We are updating this decidim installation with the new admin and the missing translations. Please, can you take a look at it?

**Comment by andreslucena** [comment]
We have a 500 on admin configuration/organization edit:
https://decidim-barcelona-pr-93.herokuapp.com/admin/organization/edit

**Comment by beagleknight** [comment]
Hi @andreslucena ! I fixed the issue you mentioned. It was an issue in production environment only, nice catch! 😄

**Comment by andreslucena** [comment]
Ok, I see everything OK. We'll do this tomorrow (Tuesday) so we can show the new interface to the technicians.

**Comment by josepjaume** [comment]
Is this ready to deploy then @andreslucena ?

**Comment by andreslucena** [comment]
Give us until tomorrow, we're reviewing this with the participatory administrators so they'll give us feedback regarding usability. It's mostly cosmetic changes but I think they're nice: 

- [ ] Change Etiqueta to Hashtag 
- [ ] Add https://decidim.barcelona/processes/ before "nom curt URL" (slug). 
- [ ] Add limitations to slug (ie it's necessary to have no spaces nor accents, etc) 
- [ ] Change promogut to destacat (the same for spanish) 
- [ ] Translate "parent" to "superior" on Category form. 

Other changes (that deserve tickets itself), but I let it here so I can copypaste later. Ignore if it's too much ;) 

- [ ] Disable formating when copy pasting to rich text format (quilljs) 
- [ ] Add headings (h1, h2) to rich text format (quilljs) 
- [ ] Automatically change browser's corrector when changing language on quilljs (I don't even know if this is possible) 
- [ ] Automatically change phases and components/functionalities when date changes (IMHO this is a big logic rewrite)

**Comment by oriolgual** [comment]
@andreslucena it would be great if you create tickets for those issues. The ones that are just about translations can be updated directly at Crowdin.

**Comment by andreslucena** [comment]
Ok, I checked them and created on #1232 #1233 #1234 #1235.

**Pull request merged**
