### PR TITLE
Static accountability fixes

### PR DESCRIPTION
**Pull request by martgnz**
#### :tophat: What? Why?
This PR updates the translations for the accountability static pages, with the suggested strings and links.

It also creates links on the homepage sections.

### CODE REVIEW

**Comment by oriolgual** [comment]
@andreslucena @xabier is it OK to merge this?

**Comment by xabier** [comment]
> @andreslucena @xabier is it OK to merge this?

sounds good to me! but I would rather wait for @andreslucena 's approval

**Comment by andreslucena** [comment]
:+1: fine by me, go ahead! 

On other hand, hound seems to be broken, and I seem to remember that we had heroku review apps on this repository

**Comment by josepjaume** [comment]
@andreslucena I think heroku review apps don't work when external PRs are issued, because of safety reasons.

**Pull request merged**
