### PR TITLE
Update decidim v0.5.1

### PR DESCRIPTION
**Pull request by beagleknight**
#### :tophat: What? Why?

Update decidim from v0.4.0 to v0.5.1. You can check the release notes below:

- [v0.5.1](https://github.com/decidim/decidim/releases/tag/v0.5.1)
- [v0.5.0](https://github.com/decidim/decidim/releases/tag/v0.5.0)
- [v0.4.4](https://github.com/decidim/decidim/releases/tag/v0.4.4)
- [v0.4.3](https://github.com/decidim/decidim/releases/tag/v0.4.3)
- [v0.4.2](https://github.com/decidim/decidim/releases/tag/v0.4.2)
- [v0.4.1](https://github.com/decidim/decidim/releases/tag/v0.4.1)

#### :pushpin: Related Issues
None

#### :clipboard: Subtasks
None

### :camera: Screenshots (optional)
N/A

#### :ghost: GIF
None

### CODE REVIEW

**Comment by beagleknight** [comment]
@andreslucena Can you take a look at this please? 😄

**Comment by josepjaume** [comment]
@beagleknight deployment's not working 😮

**Comment by mrcasals** [comment]
Review apps are destroyed after 5 days of inactivity, maybe that's what happened.

**Comment by josepjaume** [comment]
5 days? damn. I'm re-creating it again.

**Comment by beagleknight** [comment]
@andreslucena Any progress with this? 😄 
I want to upgrade decidim to `v0.5.1` but I think we must deploy this first.

**Comment by andreslucena** [comment]
Hi! Sorry @beagleknight, I've just seen this. 
Could you re-deploy the PR so I can review please? Thanks!

**Comment by mrcasals** [comment]
@andreslucena done, should be up in a few minutes :)

**Comment by andreslucena** [comment]
I think it's already up although it's giving a 500 error: 

> 500 Internal Server Error
> If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Comment by andreslucena** [comment]
There's another 500 (I don't know if related) on staging also: http://staging.decidim.codegram.com/

**Comment by beagleknight** [comment]
@andreslucena I think the 500 error in staging is not related but let me check the review app first 😄

**Comment by andreslucena** [comment]
@beagleknight ok, let me know when it's working please.

**Comment by beagleknight** [comment]
@andreslucena I have fixed the tests and I have created a review app 😄 . As I thought... the problem with the staging app is not related to this.

**Comment by andreslucena** [comment]
@beagleknight ok, I see just some minor things with i18n as usual ("Show statistics", "Announcement" on english) but nothing big.

**Comment by josepjaume** [comment]
Deprecated by #149

**Pull request closed without merging**
