### PR TITLE
Implement DataChecker to check accountability data

### PR DESCRIPTION
**Pull request by ferblape**
#### :tophat: What? Why?

This PR implements a reporter that helps comparing the differnet accountability entities with the external system where the data comes from. It uses a CSV with information about scopes, categories, and results, as documented in the Rake task.

The columns of the CSV are:

- PAM/PAD: the scope of the result
- Eje: category
- Linea: subcategory
- Actuacion: parent result
- Project: children result
- ID: the external ID of the result
- Progreso: the percentage of progress
- Peso: weight (this field only applies to projects)

### CODE REVIEW

**Comment by ferblape** [comment]
Hey, let me know what do you think about this PR. Should I document the format of the CSV better? Do you need more information about this? 

Thanks!

**Comment by josepjaume** [comment]
Hey @ferblape - sorry for not reviewing this before. Maybe a bit of documentation about the input CSV would be helpful?

**Comment by ferblape** [comment]
You are right, PR updated.

**Comment by josepjaume** [comment]
Nice! Merging this, thanks @ferblape

**Pull request merged**
