### PR TITLE
Widgets

### PR DESCRIPTION
**Pull request by oriolgual**
#### :tophat: What? Why?

Since we don't have review apps for the main Decidim repo I'm creating the PR so we can test the widgets feature in a staging environment.

### CODE REVIEW

**Comment by andreslucena** [comment]
How are we doing with this feature? I didn't have time to review this on the temporary deployed app, could you please deploy it again?

**Comment by oriolgual** [comment]
@andreslucena I think @josepjaume had some concerns on the current implementation. When he and @beagleknight agree on something we'll redeploy this.

**Comment by andreslucena** [comment]
Ok, let me know when there is something to review on our side.

**Comment by beagleknight** [comment]
I'm closing this in favor of #108

**Pull request closed without merging**
