### PR TITLE
Update decidim to v0.4.1

### PR DESCRIPTION
**Pull request by beagleknight**
#### :tophat: What? Why?

Upgrade decidim to the latest version. [View release notes](https://github.com/decidim/decidim/releases/tag/v0.4.1)

#### :pushpin: Related Issues
None

#### :clipboard: Subtasks
None

### :camera: Screenshots (optional)
N/A

#### :ghost: GIF
None

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I'm noticing that since decidim `0.4.0` we haven't released all plugins in sync: https://rubygems.org/search?query=decidim. Is that intentional? Is that related to this PR pointing to a git tag or being blocked?

**Comment by beagleknight** [comment]
It wasn't intentional 😞  I only have publish access for `decidim`, `decidim-dev` and `decidim-core`. We need to wait until @josepjaume come back on Monday. Sorry about the inconvenience!

**Comment by beagleknight** [comment]
I also want to update this installation to the latest version (v0.4.3) but I prefer grabbing the gem from rubygems if possible!

**Comment by deivid-rodriguez** [comment]
Aaaaaah, I understand now! Thank you @beagleknight!

**Comment by beagleknight** [comment]
Closing this in favor of https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/140

**Pull request closed without merging**
