### PR TITLE
Add missing projects & proposals locales

### PR DESCRIPTION
**Pull request by oriolgual**
#### :tophat: What? Why?

This is a temporary fix until `Decidim` fixes this missing translation. 

#### :pushpin: Related Issues
- Related to https://github.com/AjuntamentdeBarcelona/decidim/issues/1191

### CODE REVIEW

**Comment by oriolgual** [comment]
@andreslucena it seems we can't deploy this until we deploy #89 since the graphql gem version (1.5.1) was removed from Rubygems. Neither Travis or Heroku can build the environment :/ (I'm waiting on Heroku but I'll possibly error)

**Comment by oriolgual** [comment]
Yup, the deployment failed 😣

**Comment by andreslucena** [comment]
Maybe we can also add the specs and seeds for this kind of Resources so if we have a regression we can detect it on tests?

**Comment by oriolgual** [comment]
I've updated this PR to also update the dependency on GraphQL so at least we can deploy it.

**Comment by oriolgual** [comment]
@andreslucena yes! We've done it here:

https://github.com/AjuntamentdeBarcelona/decidim/pull/1193
and
https://github.com/AjuntamentdeBarcelona/decidim/pull/1192

**Comment by oriolgual** [comment]
@andreslucena the review app is ready! https://decidim-barcelona-pr-90.herokuapp.com

**Comment by mrcasals** [comment]
Note that we noticed that we don't need to merge #89 before merging this, so wan deliver this hotfix while we review all the other changes @andreslucena

**Comment by oriolgual** [comment]
Seems to be working OK: https://decidim-barcelona-pr-90.herokuapp.com/processes/3/f/12/results/7

**Pull request merged**
